### ISSUE TITLE
Use new version on Nessie

### ISSUE THREAD

**Issue by halvardssm** [22mahmoud/deno_crud_jwt#1]
Hi! Two days ago I upgraded Nessie to v0.5.0. This version brought with it a lot of breaking changes which you might want to take a look at 😄 

Luckily it is quite easy to update to the new version. In the migrations, you will only have to change from `schema.create` to `return new Schema().create` (Schema is now exported from https://deno.land/x/nessie/qb.ts), and regarding the config file, you will have to import the client from `import {ClientPostgreSQL} from https://deno.land/x/nessie/mod.ts`.

Hope you like the new version!

**Comment by mashrafdev** [comment]
Hey, Good job dude.
I'll check it.

**Comment by 22mahmoud** [comment]
#2

**Comment by halvardssm** [comment]
Thanks! If you have any feedback, feel free to let me know!
